/**
 * CONCLAIVE Core Types
 */

export const StageStatus = {
  NOT_STARTED: 'NOT_STARTED',
  RUNNING: 'RUNNING',
  COMPLETE: 'COMPLETE',
  FAILED: 'FAILED'
};

export const ConclaveMode = {
  STANDARD: 'STANDARD',
  REDLINE: 'REDLINE'
};

export const EmergencePosition = {
  PROCEED: 'PROCEED',
  PROCEED_WITH_CONDITIONS: 'PROCEED WITH CONDITIONS',
  MODIFY: 'MODIFY',
  INVESTIGATE: 'INVESTIGATE',
  DEFER: 'DEFER',
  DO_NOT_PROCEED: 'DO NOT PROCEED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT EVIDENCE'
};
